import type { OmesThemeTokens } from './tokens'

const CLASSIC_FONT_FAMILY =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif"

/** 微软风格改造前的 OMES 原始主题 token */
export const classicOmesTokens = {
  colorPrimary: '#1677ff',
  colorPrimaryHover: '#4096ff',
  colorPrimaryActive: '#0958d9',
  colorPrimaryBg: '#e6f4ff',
  colorPrimaryBgHover: '#f5f9ff',
  colorPrimaryBorder: '#d6e4ff',

  colorBgLayout: '#f5f5f5',
  colorBgContainer: '#ffffff',
  colorWhite: '#ffffff',
  colorBgElevated: '#fafafa',
  colorBgSpotlight: '#fafbfd',
  colorBgMuted: '#fafbfc',
  colorBgToolbarFrom: '#f8fafc',
  colorBgToolbarTo: '#f5f7fa',
  colorBgTableHead: '#f6f8fb',
  colorBgTableHeadAlt: '#fafafa',
  colorBgTableHover: '#f5f9ff',
  colorBgTableHoverAlt: '#f8fbff',
  colorBgStandalone: '#060b12',

  colorBorder: '#f0f0f0',
  colorBorderSecondary: '#eef1f6',
  colorBorderTertiary: '#e8ecf2',
  colorBorderHover: '#e8e8e8',

  colorText: 'rgba(0, 0, 0, 0.88)',
  colorTextSecondary: 'rgba(0, 0, 0, 0.65)',
  colorTextTertiary: 'rgba(0, 0, 0, 0.55)',
  colorTextQuaternary: 'rgba(0, 0, 0, 0.45)',
  colorTextPlaceholder: 'rgba(0, 0, 0, 0.35)',
  colorTextHeading: 'rgba(0, 0, 0, 0.85)',
  colorTextLabel: 'rgba(0, 0, 0, 0.75)',

  colorSuccess: '#52c41a',
  colorSuccessBg: '#f6ffed',
  colorSuccessBorder: '#b7eb8f',
  colorWarning: '#fa8c16',
  colorError: '#ff4d4f',
  colorInfo: '#1677ff',

  colorAccentPurpleFrom: '#722ed1',
  colorAccentPurpleTo: '#9254de',
  colorAccentOrangeFrom: '#fa8c16',
  colorAccentOrangeTo: '#ffa940',
  colorAccentOrangeLightTo: '#ffc069',
  colorAccentCyanFrom: '#13c2c2',
  colorAccentCyanTo: '#36cfc9',
  colorAccentCyanBg: '#e6fffb',
  colorAccentCyanBorder: '#87e8de',

  colorChartPalette0: '#1677ff',
  colorChartPalette1: '#722ed1',
  colorChartPalette2: '#13c2c2',
  colorChartPalette3: '#eb2f96',
  colorChartPalette4: '#fa8c16',
  colorChartPalette5: '#52c41a',

  fontFamilyBase: CLASSIC_FONT_FAMILY,
  fontSizeBase: '14px',
  lineHeightBase: '22px',
  fontWeightRegular: 400,
  fontWeightSemibold: 600,
  borderRadiusSmall: '2px',
  borderRadiusMedium: '6px',
  borderRadiusLarge: '10px',
  borderRadiusXLarge: '10px',
  shadow2: '0 1px 2px rgba(0, 0, 0, 0.03)',
  shadow4: '0 1px 3px rgba(15, 23, 42, 0.04)',
  shadow8: '0 8px 22px rgba(22, 119, 255, 0.14)',
  shadow16: '0 8px 22px rgba(22, 119, 255, 0.14)',
  spacingHorizontalM: '12px',
  spacingVerticalM: '12px',
} as const satisfies OmesThemeTokens

export const classicAntdThemeConfig = {
  token: {
    colorPrimary: classicOmesTokens.colorPrimary,
    colorPrimaryHover: classicOmesTokens.colorPrimaryHover,
    colorPrimaryActive: classicOmesTokens.colorPrimaryActive,
    colorSuccess: classicOmesTokens.colorSuccess,
    colorWarning: classicOmesTokens.colorWarning,
    colorError: classicOmesTokens.colorError,
    colorInfo: classicOmesTokens.colorInfo,
    colorTextBase: '#000000',
    colorBgBase: '#ffffff',
    colorBgLayout: classicOmesTokens.colorBgLayout,
    colorBgContainer: classicOmesTokens.colorBgContainer,
    colorBgElevated: classicOmesTokens.colorBgElevated,
    colorText: classicOmesTokens.colorText,
    colorTextSecondary: classicOmesTokens.colorTextSecondary,
    colorTextTertiary: classicOmesTokens.colorTextQuaternary,
    colorTextQuaternary: classicOmesTokens.colorTextQuaternary,
    colorBorder: classicOmesTokens.colorBorder,
    colorBorderSecondary: classicOmesTokens.colorBorderSecondary,
    borderRadius: 6,
    borderRadiusLG: 10,
    borderRadiusSM: 6,
    fontFamily: CLASSIC_FONT_FAMILY,
    fontSize: 14,
    controlHeight: 32,
    wireframe: false,
  },
} as const
