FROM openjdk:21-jdk
ADD target/*.jar omes-admin.jar
ENTRYPOINT java $CATALINA_OPTS -Dnacos.use.cloud.namespace.parsing=false -Dnacos.use.endpoint.parsing.rule=false -Duser.timezone=GMT+08 -Dspring.profiles.active=prod -jar omes-admin.jar