<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ourexists.omes</groupId>
        <artifactId>omes-iomp</artifactId>
            <version>1.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>omes-iomp-ucenter</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>omes-iomp-ucenter-feign</module>
        <module>omes-iomp-ucenter-model</module>
        <module>omes-iomp-ucenter-server</module>
    </modules>
</project>
